// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./components/SetupWizardLoading copy.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectBubble: typeof import('./components/SelectBubble.vue')['default']
    SetupEducationModal: typeof import('./components/SetupEducationModal.vue')['default']
    SetupModal: typeof import('./components/SetupModal.vue')['default']
    SetupModalButton: typeof import('./components/SetupModalButton.vue')['default']
    SetupModalFooter: typeof import('./components/SetupModalFooter.vue')['default']
    SetupWizard: typeof import('./components/SetupWizard.vue')['default']
    SetupWizardAvailability: typeof import('./components/SetupWizardAvailability.vue')['default']
    SetupWizardCovidPreferences: typeof import('./components/SetupWizardCovidPreferences.vue')['default']
    SetupWizardEducation: typeof import('./components/SetupWizardEducation.vue')['default']
    SetupWizardFinished: typeof import('./components/SetupWizardFinished.vue')['default']
    SetupWizardLoading: typeof import('./components/SetupWizardLoading.vue')['default']
    SetupWizardLocation: typeof import('./components/SetupWizardLocation.vue')['default']
    SignUpModal: typeof import('./components/SignUpModal.vue')['default']
  }
}
